import { createContext, useContext, useState, type ReactNode } from 'react';
export type Module = 'customers' | 'leads' | 'opportunities' | 'follow-ups' | 'activities' | 'users' | 'audit';
export type Role = 'Admin' | 'Manager' | 'Sales Executive';
export type CRMRecord = { id: string; name: string; company: string; email: string; phone: string; status: string; owner: string; date: string; amount: number; probability: number; source: string; type: string; notes: string; role: Role; address: string; city: string; state: string; priority: string; related: string; };
export const today = () => new Date().toISOString().slice(0,10);
export const futureDate = (days: number) => { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0,10); };
export const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export const shortMoney = (n:number) => n >= 1000000 ? `$${(n/1000000).toFixed(2)}M` : n >= 1000 ? `$${(n/1000).toFixed(0)}K` : money(n);
export const owners = ['Alex Morgan','Sarah Wilson','James Carter','Emma Davis'];
export const statuses:Record<Module,string[]> = { customers:['Active','Inactive'], leads:['New','Contacted','Qualified','Unqualified','Converted','Lost'], opportunities:['Qualification','Proposal','Negotiation','Won','Lost'], 'follow-ups':['Planned','Completed','Missed','Cancelled'], activities:['Planned','Completed','Cancelled'], users:['Active','Inactive','Locked'], audit:['Success','Failed'] };
export const blankRecord = (): CRMRecord => ({id:'',name:'',company:'',email:'',phone:'',status:'',owner:'Alex Morgan',date:futureDate(7),amount:0,probability:50,source:'Website',type:'Call',notes:'',role:'Sales Executive',address:'',city:'',state:'',priority:'Medium',related:''});
function row(id:string,name:string, company:string, options:Partial<CRMRecord>={}):CRMRecord { return {...blankRecord(),id,name,company,email:`${name.toLowerCase().replaceAll(' ','.')}@${company.toLowerCase().replace(/[^a-z]/g,'')}.com`,phone:`+1 415 555 ${id.replace(/\D/g,'').padStart(4,'0')}`,status:'Active',...options}; }
export const initialData: Record<Module,CRMRecord[]> = {
 customers:[row('CUS-1001','Olivia Rhye','Acme Corporation',{owner:'Sarah Wilson',city:'San Francisco',state:'California',address:'100 Market Street',notes:'Enterprise customer. Interested in expanding to additional teams.'}),row('CUS-1002','Phoenix Baker','Globex Industries',{owner:'James Carter',city:'New York'}),row('CUS-1003','Lana Steiner','Stark Industries',{owner:'Emma Davis'}),row('CUS-1004','Demi Wilkinson','Notion Labs',{owner:'Alex Morgan'}),row('CUS-1005','Drew Cano','Linear',{status:'Inactive'}),row('CUS-1006','Natali Craig','Figma',{owner:'Sarah Wilson'}),row('CUS-1007','Orlando Diggs','Vercel',{owner:'James Carter'}),row('CUS-1008','Andi Lane','Loom',{owner:'Emma Davis'})],
 leads:[row('LD-2001','Michael Foster','Acme Corporation',{status:'Qualified',owner:'Sarah Wilson',source:'Referral',amount:48000,priority:'High'}),row('LD-2002','Lindsay Walton','Globex Industries',{status:'Contacted',owner:'James Carter',source:'Website',amount:32500}),row('LD-2003','Courtney Henry','Stark Industries',{status:'New',owner:'Emma Davis',source:'LinkedIn',amount:72000,priority:'High'}),row('LD-2004','Tom Cook','Notion Labs',{status:'Qualified',owner:'Alex Morgan',source:'Website',amount:18000}),row('LD-2005','Whitney Francis','Linear',{status:'New',owner:'Sarah Wilson',source:'Event',amount:25000}),row('LD-2006','Leslie Alexander','Figma',{status:'Converted',owner:'James Carter',source:'Referral',amount:42000}),row('LD-2007','Leonard Krasner','Vercel',{status:'Lost',owner:'Emma Davis',amount:12000}),row('LD-2008','Floyd Miles','Loom',{status:'Contacted',owner:'Alex Morgan',amount:35000})],
 opportunities:[row('OP-3001','Enterprise expansion','Acme Corporation',{status:'Negotiation',owner:'Sarah Wilson',amount:85000,probability:80,related:'Acme Corporation',date:futureDate(12)}),row('OP-3002','Annual platform license','Globex Industries',{status:'Proposal',owner:'James Carter',amount:64000,probability:60,related:'Globex Industries',date:futureDate(20)}),row('OP-3003','CRM implementation','Stark Industries',{status:'Qualification',owner:'Emma Davis',amount:42000,probability:30,related:'Stark Industries'}),row('OP-3004','Team workspace upgrade','Notion Labs',{status:'Won',owner:'Alex Morgan',amount:38000,probability:100,related:'Notion Labs'}),row('OP-3005','Growth plan renewal','Linear',{status:'Proposal',owner:'Alex Morgan',amount:27500,probability:55,related:'Linear'}),row('OP-3006','Design team rollout','Figma',{status:'Negotiation',owner:'Sarah Wilson',amount:56000,probability:75,related:'Figma'}),row('OP-3007','Developer workspace','Vercel',{status:'Lost',owner:'James Carter',amount:22000,probability:0,related:'Vercel'}),row('OP-3008','Business plan','Loom',{status:'Qualification',owner:'Emma Davis',amount:32000,probability:25,related:'Loom'})],
 'follow-ups':[row('FU-4001','Discuss enterprise pricing','Acme Corporation',{type:'Call',status:'Planned',owner:'Sarah Wilson',date:today(),related:'Acme Corporation',notes:'Review the updated enterprise proposal.'}),row('FU-4002','Product demo & walkthrough','Globex Industries',{type:'Meeting',status:'Planned',owner:'James Carter',date:today(),related:'Globex Industries'}),row('FU-4003','Send revised proposal','Stark Industries',{type:'Email',status:'Planned',owner:'Emma Davis',date:futureDate(1),related:'Stark Industries'}),row('FU-4004','Check in on onboarding','Notion Labs',{type:'Call',status:'Planned',owner:'Alex Morgan',date:futureDate(2),related:'Notion Labs'}),row('FU-4005','Review renewal terms','Linear',{type:'Meeting',status:'Completed',owner:'Alex Morgan',date:today(),related:'Linear'})],
 activities:[row('ACT-5001','Discovery call completed','Acme Corporation',{type:'Call',status:'Completed',owner:'Sarah Wilson',date:today(),notes:'Confirmed budget and decision-makers.'}),row('ACT-5002','Send product overview','Globex Industries',{type:'Email',status:'Planned',owner:'James Carter',date:futureDate(1)}),row('ACT-5003','Prepare pricing proposal','Stark Industries',{type:'Task',status:'Planned',owner:'Emma Davis',date:futureDate(2)})],
 users:[row('USR-6001','Alex Morgan','Sales team',{email:'alex@acxiomcrm.com',role:'Admin'}),row('USR-6002','Sarah Wilson','Sales team',{email:'sarah@acxiomcrm.com',role:'Manager'}),row('USR-6003','James Carter','Sales team',{email:'james@acxiomcrm.com'}),row('USR-6004','Emma Davis','Sales team',{email:'emma@acxiomcrm.com'}),row('USR-6005','Daniel Kim','Sales team',{email:'daniel@acxiomcrm.com',status:'Inactive'})],
 audit:[row('AUD-7001','Updated lead status','Lead Management',{owner:'Sarah Wilson',status:'Success',type:'Update',related:'LD-2001',date:today(),notes:'Status changed from Contacted to Qualified.'}),row('AUD-7002','Created opportunity','Opportunities',{owner:'James Carter',status:'Success',type:'Create',related:'OP-3002',date:today()}),row('AUD-7003','Signed in','Authentication',{owner:'Alex Morgan',status:'Success',type:'Login',date:today()}),row('AUD-7004','Completed follow-up','Follow-ups',{owner:'Emma Davis',status:'Success',type:'Update',related:'FU-4005',date:today()})],
};
type CRMContextValue = { data:Record<Module,CRMRecord[]>; role:Role; setRole:(r:Role)=>void; signedIn:boolean; setSignedIn:(v:boolean)=>void; save:(module:Module,record:CRMRecord)=>void; remove:(module:Module,id:string)=>void; convert:(record:CRMRecord)=>void; scoped:(module:Module)=>CRMRecord[]; };
const CRMContext=createContext<CRMContextValue|null>(null);
export function CRMProvider({children}:{children:ReactNode}) { const [data,setData]=useState(initialData); const [role,setRole]=useState<Role>('Admin'); const [signedIn,setSignedIn]=useState(true);
 const audit=(old:Record<Module,CRMRecord[]>,action:string,module:Module,id:string)=>[row(`AUD-${Date.now()}`,`${action} ${module==='follow-ups'?'follow-up':module.slice(0,-1)}`,module,{owner:'Alex Morgan',status:'Success',type:action,related:id,date:today(),notes:`${action} action recorded in the sample workspace.`}),...old.audit];
 const save=(module:Module,record:CRMRecord)=>setData(old=>{const exists=old[module].some(r=>r.id===record.id);const saved={...record,id:record.id||`${module.slice(0,3).toUpperCase()}-${Date.now().toString().slice(-6)}`};return {...old,[module]:exists?old[module].map(r=>r.id===saved.id?saved:r):[saved,...old[module]],audit:audit(old,exists?'Update':'Create',module,saved.id)};});
 const remove=(module:Module,id:string)=>setData(old=>({...old,[module]:old[module].filter(r=>r.id!==id),audit:audit(old,'Delete',module,id)}));
 const convert=(record:CRMRecord)=>setData(old=>{const existing=old.customers.find(r=>r.email===record.email||r.phone===record.phone);const customer={...record,id:`CUS-${Date.now().toString().slice(-6)}`,status:'Active'};return {...old,customers:existing?old.customers:[customer,...old.customers],leads:old.leads.map(r=>r.id===record.id?{...r,status:'Converted'}:r),audit:audit(old,'Convert','leads',record.id)};});
 const scoped=(module:Module)=>role==='Sales Executive'?data[module].filter(r=>r.owner==='Alex Morgan'):data[module];
 return <CRMContext.Provider value={{data,role,setRole,signedIn,setSignedIn,save,remove,convert,scoped}}>{children}</CRMContext.Provider>;
}
export function useCRM() { const ctx=useContext(CRMContext); if(!ctx) throw new Error('CRMProvider is required');return ctx; }
export function exportCSV(rows:CRMRecord[],name:string) { const cols=['id','name','company','email','phone','status','owner','date','amount','probability','type','role','notes'] as const;const text=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]).replaceAll('"','""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`acxiom-${name}.csv`;a.click();URL.revokeObjectURL(url); }
export function metadata(title:string,description:string) { return {meta:[{title:`${title} — AcxiomCRM`},{name:'description',content:description},{property:'og:title',content:`${title} — AcxiomCRM`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}; }
