import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Users, ContactRound, ChartNoAxesCombined, Wallet, ArrowRight, ArrowUpRight, Phone, Video, Mail, Clock3, MoreHorizontal, CalendarDays, Check, CircleCheck } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell } from 'recharts';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { useCRM, money, shortMoney, today, exportCSV, type CRMRecord } from '@/lib/crm-data';
import { Avatar, Status, PageHeading, Metric } from './common';
import { RecordForm } from './record-form';
const monthly=[{month:'May',revenue:22000,target:33000},{month:'Jun',revenue:38000,target:47000},{month:'Jul',revenue:34000,target:40000},{month:'Aug',revenue:56000,target:66000},{month:'Sep',revenue:48000,target:59000},{month:'Oct',revenue:79000,target:92000}];
const week=[{month:'Mon',revenue:4000,target:6000},{month:'Tue',revenue:9000,target:11000},{month:'Wed',revenue:6000,target:9000},{month:'Thu',revenue:14000,target:18000},{month:'Fri',revenue:12000,target:16000},{month:'Sat',revenue:19000,target:23000}];
export function Dashboard() {const {scoped,save,role}=useCRM();const [period,setPeriod]=useState('This month');const [range,setRange]=useState('Last 6 months');const [form,setForm]=useState(false);const customers=scoped('customers');const leads=scoped('leads');const opps=scoped('opportunities');const open=opps.filter(r=>!['Won','Lost'].includes(r.status));const follows=scoped('follow-ups').filter(r=>r.status==='Planned');const pipeline=open.reduce((sum,r)=>sum+r.amount,0);const leadData=['New','Contacted','Qualified','Converted','Lost'].map((name,i)=>({name,value:leads.filter(r=>r.status===name).length,color:`var(--${['chart-1','chart-4','chart-5','chart-3','border'][i]})`}));const won=opps.filter(r=>r.status==='Won').reduce((s,r)=>s+r.amount,0);const chartData=range==='This week'?week:monthly;const periodMultiplier=period==='Today'?.14:period==='This week'?.4:1;const displayChart=chartData.map(r=>({...r,revenue:Math.round(r.revenue*periodMultiplier),target:Math.round(r.target*periodMultiplier)}));
 return <div className="page"><PageHeading title="Dashboard" description="Welcome back, Alex. Here’s what’s happening with your sales." rows={opps} onAdd={()=>setForm(true)} addLabel="Add lead"><select className="period-select" aria-label="Dashboard period" value={period} onChange={e=>setPeriod(e.target.value)}><option>Today</option><option>This week</option><option>This month</option></select></PageHeading><div className="kpi-grid"><Metric label="Total customers" value={customers.length.toLocaleString()} change="12.8%" icon={Users} tone="green"/><Metric label="Open leads" value={leads.filter(r=>!['Lost','Converted','Unqualified'].includes(r.status)).length} change="8.2%" icon={ContactRound} tone="blue"/><Metric label="Open opportunities" value={open.length} change="16.4%" icon={ChartNoAxesCombined} tone="violet"/><Metric label="Pipeline value" value={shortMoney(pipeline)} change="24.6%" icon={Wallet} tone="amber"/></div>
 <div className="chart-grid"><section className="panel"><div className="panel-heading"><div><h2>Sales overview</h2><p>Your revenue performance over time</p></div><select className="select-control" aria-label="Sales chart range" value={range} onChange={e=>setRange(e.target.value)}><option>Last 6 months</option><option>This week</option></select></div><div className="flex flex-wrap justify-between items-center gap-3 pr-6"><div className="sales-summary"><strong>{money(displayChart.reduce((s,r)=>s+r.revenue,0))}</strong><span><ArrowUpRight size={10} className="inline"/>18.6%</span></div><div className="chart-legend"><span><i className="legend-dot"/>Revenue</span><span><i className="legend-dot secondary"/>Target</span></div></div><div className="sales-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={displayChart} margin={{top:15,right:8,left:0,bottom:0}}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-1)" stopOpacity={.15}/><stop offset="100%" stopColor="var(--chart-1)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:'var(--muted-foreground)',fontSize:10}} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{fill:'var(--muted-foreground)',fontSize:9}} tickFormatter={v=>`$${v/1000}k`} width={47} ticks={period==='This month'?[0,25000,50000,75000,100000]:undefined}/><Tooltip formatter={(v:number)=>money(v)} contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:6,fontSize:11}}/><Area type="monotone" dataKey="target" name="Target" stroke="var(--chart-3)" strokeWidth={1.5} strokeDasharray="4 4" fill="transparent"/><Area type="monotone" dataKey="revenue" name="Revenue" stroke="var(--chart-1)" strokeWidth={2.5} fill="url(#revenue-fill)"/></AreaChart></ResponsiveContainer></div><div className="panel-footer"><span>Sample revenue · {period.toLowerCase()}</span><Button asChild variant="link" size="sm" className="h-auto p-0 text-[10px]"><Link to="/reports">View report<ArrowRight size={11}/></Link></Button></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Lead distribution</h2><p>A snapshot of your lead pipeline</p></div><Button variant="ghost" size="icon" title="Export lead distribution" aria-label="Export lead distribution" onClick={()=>exportCSV(leads,'lead-distribution')}><MoreHorizontal/></Button></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={leadData} dataKey="value" innerRadius={61} outerRadius={79} startAngle={90} endAngle={-270} paddingAngle={3} strokeWidth={0}>{leadData.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:6,fontSize:11}}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{leads.length}</strong><span>Total leads</span></div></div><div className="lead-legend">{leadData.map((r,i)=><div key={r.name}><i className={`dot dot-${i}`}/>{r.name}<strong>{r.value}</strong></div>)}</div></section></div>
 <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Recent leads</h2><p>Your newest connections, all in one place</p></div><Button asChild variant="link" size="sm" className="h-auto p-0 text-[10px]"><Link to="/leads">View all<ArrowRight/></Link></Button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Lead / company</th><th>Status</th><th>Value</th><th>Owner</th></tr></thead><tbody>{leads.slice(0,5).map((lead,i)=><tr key={lead.id}><td><div className="name">{lead.name}</div><div className="sub">{lead.company}</div></td><td><Status value={lead.status}/></td><td className="font-medium">{money(lead.amount)}</td><td><Avatar name={lead.owner} className={['','amber','blue','violet'][i%4]}/></td></tr>)}</tbody></table></div><div className="panel-footer"><span>Showing {Math.min(5,leads.length)} of {leads.length} leads</span><span>Updated just now</span></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Upcoming follow-ups</h2><p>Keep the conversation going</p></div><Button asChild variant="link" size="sm" className="h-auto p-0 text-[10px]"><Link to="/follow-ups">View all<ArrowRight/></Link></Button></div>{follows.slice(0,4).map((r,i)=>{const Icon=r.type==='Meeting'?Video:r.type==='Email'?Mail:Phone;return <div className="follow-item" key={r.id}><span className={`follow-icon ${r.type==='Meeting'?'meeting':r.type==='Email'?'email':''}`}><Icon size={15}/></span><div className="follow-content"><h3>{r.name}</h3><p>{r.company}</p><small><Clock3 size={10}/>{r.date===today()?'Today':r.date} · {['10:30 AM','2:00 PM','11:00 AM','3:30 PM'][i]}</small></div><Button variant="ghost" size="icon" title="Mark complete" aria-label={`Complete ${r.name}`} onClick={()=>{save('follow-ups',{...r,status:'Completed'});toast.success('Follow-up completed');}}><Check className="text-muted-foreground"/></Button></div>;})}{!follows.length&&<div className="empty"><CircleCheck className="mx-auto mb-3"/>You’re all caught up.</div>}</section></div>
 <div className="mt-6 flex flex-wrap gap-6 text-[11px] text-muted-foreground"><span>Won opportunities <strong className="text-foreground ml-2">{opps.filter(r=>r.status==='Won').length}</strong></span><span>Lost opportunities <strong className="text-foreground ml-2">{opps.filter(r=>r.status==='Lost').length}</strong></span><span>Won revenue <strong className="text-foreground ml-2">{money(won)}</strong></span><span>Pending follow-ups <strong className="text-foreground ml-2">{follows.length}</strong></span></div><footer className="page-footer"><span>© {new Date().getFullYear()} AcxiomCRM. All rights reserved.</span><span><i className="live-dot"/>Sample workspace · {role}</span></footer>{form&&<RecordForm module="leads" onClose={()=>setForm(false)}/>}</div>;
}
