import { useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { blankRecord, owners, statuses, today, useCRM, type CRMRecord, type Module } from '@/lib/crm-data';
export function RecordForm({module,record,onClose}:{module:Module;record?:CRMRecord;onClose:()=>void}) { const {save,data}=useCRM();const [values,setValues]=useState<CRMRecord>(record||{...blankRecord(),status:statuses[module][0]});const [errors,setErrors]=useState<Record<string,string>>({});const isContact=module==='customers'||module==='leads';const isOpportunity=module==='opportunities';const isFollow=module==='follow-ups'||module==='activities';const isUser=module==='users';
 const set=(key:keyof CRMRecord,value:string)=>setValues(old=>({...old,[key]:key==='amount'||key==='probability'?Number(value):value}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();const err:Record<string,string>={};if(!values.name.trim()) err.name=`${isContact?'Name':'Subject'} is required.`;if(values.name.length>100) err.name='Maximum 100 characters.';
 if(isContact||isUser){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) err.email='Enter a valid email address.'; if(data[module].some(r=>r.id!==values.id&&r.email.toLowerCase()===values.email.toLowerCase()))err.email='This email is already in use.';}
 if(isContact){if(!/^\+?[\d\s()-]{7,20}$/.test(values.phone)||values.phone.replace(/\D/g,'').length<7)err.phone='Enter a valid phone number.';if(data[module].some(r=>r.id!==values.id&&r.phone.replace(/\D/g,'')===values.phone.replace(/\D/g,'')))err.phone='This phone number is already in use.';}
 if(isOpportunity){if(!values.related)err.related='Select a customer.';if(values.amount<=0)err.amount='Opportunity amount must be greater than 0.';if(values.probability<0||values.probability>100)err.probability='Probability must be between 0 and 100.';if(!['Won','Lost'].includes(values.status)&&values.date<today())err.date='Expected close date cannot be in the past.';}
 if(module==='leads'&&values.amount<0)err.amount='Expected value cannot be negative.';
 if(isFollow&&values.status==='Planned'&&values.date<today())err.date='Follow-up date cannot be earlier than today.';if((isFollow||isOpportunity)&&!values.date)err.date='Date is required.';if(!statuses[module].includes(values.status))err.status='Select a valid status.';
 setErrors(err);if(Object.keys(err).length)return;save(module,{...values,name:values.name.trim(),company:isOpportunity||isFollow?values.related||values.company:values.company});toast.success(`${record?'Changes saved':'Record created'} successfully`);onClose();};
 function field(key:keyof CRMRecord,label:string,type='text',options?:string[],full=false){return <div className={`field ${full?'full':''}`} key={key}><label htmlFor={`field-${key}`}>{label}</label>{options?<select className="select-control" id={`field-${key}`} value={String(values[key])} onChange={e=>set(key,e.target.value)}>{options.map(v=><option key={v} value={v}>{v||'Select a customer'}</option>)}</select>:key==='notes'?<textarea id={`field-${key}`} value={values.notes} onChange={e=>set(key,e.target.value)} maxLength={2000}/>:<Input id={`field-${key}`} type={type} value={String(values[key])} onChange={e=>set(key,e.target.value)} maxLength={type==='text'?150:undefined} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`error-${key}`:undefined}/>} {errors[key]&&<span className="field-error" id={`error-${key}`}>{errors[key]}</span>}</div>;}
 const label=module==='follow-ups'?'follow-up':module==='activities'?'activity':module.slice(0,-1);
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="form-dialog"><DialogTitle>{record?'Edit':'New'} {label}</DialogTitle><DialogDescription>{record?'Update the record details.':'Add a new record to your workspace.'}</DialogDescription><form onSubmit={submit} noValidate><div className="form-grid">{field('name',isOpportunity?'Opportunity name':isFollow?'Subject':'Full name')}{isContact&&field('company','Company name')}{(isContact||isUser)&&field('email','Email address','email')}{isContact&&field('phone','Phone number','tel')}{(isOpportunity||isFollow)&&field('related','Related customer / company','text',['',...data.customers.map(r=>r.company)])}{field('status',isOpportunity?'Pipeline stage':'Status','text',statuses[module])}{!isUser&&field('owner','Assigned to','text',owners)}{isContact&&module==='customers'&&<>{field('address','Address')}{field('city','City')}{field('state','State')}</>}{module==='leads'&&<>{field('source','Lead source','text',['Website','Referral','LinkedIn','Event','Outbound','Other'])}{field('priority','Priority','text',['Low','Medium','High'])}{field('amount','Expected value ($)','number')}</>}{isOpportunity&&<>{field('amount','Amount ($)','number')}{field('probability','Probability (%)','number')}{field('date','Expected close date','date')}{field('source','Source','text',['Website','Referral','LinkedIn','Event','Outbound','Other'])}</>}{isFollow&&<>{field('type','Activity type','text',['Call','Meeting','Email','Task'])}{field('date',module==='follow-ups'?'Follow-up date':'Activity date','date')}</>}{isUser&&field('role','Primary role','text',['Admin','Manager','Sales Executive'])}{field('notes','Notes','text',undefined,true)}</div><div className="form-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">{record?'Save changes':`Create ${label}`}</Button></div></form></DialogContent></Dialog>;
}
