import { useState } from 'react';
import { Search, Plus, Pencil, Trash2, Eye, ArrowRightLeft, Check, ChevronLeft, ChevronRight, Download, ArrowUpDown, List, Columns3, Shield } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useCRM, money, statuses, exportCSV, type Module, type CRMRecord } from '@/lib/crm-data';
import { Avatar, Status, PageHeading } from './common';
import { RecordForm } from './record-form';
const config:Record<Module,{title:string;description:string;singular:string}>={customers:{title:'Customers',description:'Build stronger relationships with every customer.',singular:'customer'},leads:{title:'Leads',description:'Turn your next conversation into an opportunity.',singular:'lead'},opportunities:{title:'Opportunities',description:'Keep your deals moving and your pipeline growing.',singular:'opportunity'},'follow-ups':{title:'Follow-ups',description:'The right conversation, at the right time.',singular:'follow-up'},activities:{title:'Activities',description:'Stay on top of your calls, meetings, emails, and tasks.',singular:'activity'},users:{title:'Users & roles',description:'Manage your team and their workspace access.',singular:'user'},audit:{title:'Audit log',description:'A clear record of your workspace’s activity.',singular:'event'}};
export function RecordsPage({module}:{module:Module}) { const {scoped,save,remove,convert,role}=useCRM();const [search,setSearch]=useState('');const [filter,setFilter]=useState('All statuses');const [owner,setOwner]=useState('All owners');const [page,setPage]=useState(1);const [sort,setSort]=useState(false);const [board,setBoard]=useState(module==='opportunities');const [form,setForm]=useState<CRMRecord|true|null>(null);const [detail,setDetail]=useState<CRMRecord|null>(null);const [deleting,setDeleting]=useState<CRMRecord|null>(null);const settings=config[module];const forbidden=(module==='users'||module==='audit')&&role!=='Admin';
 const rows=scoped(module).filter(r=>[r.name,r.company,r.email,r.id,r.owner,r.type].join(' ').toLowerCase().includes(search.toLowerCase())&&(filter==='All statuses'||r.status===filter)&&(owner==='All owners'||r.owner===owner)).sort((a,b)=>sort?a.name.localeCompare(b.name):0);const pageCount=Math.max(1,Math.ceil(rows.length/7));const safePage=Math.min(page,pageCount);const visible=rows.slice((safePage-1)*7,safePage*7);const isContact=module==='customers'||module==='leads';const isTask=module==='follow-ups'||module==='activities';const isAudit=module==='audit';
 const changeStatus=(r:CRMRecord,status:string)=>{save(module,{...r,status,probability:status==='Won'?100:status==='Lost'?0:r.probability});toast.success('Status updated');};
 if(forbidden)return <div className="page"><PageHeading title="Access restricted" description="This section is available to administrators."/><Shield className="text-muted-foreground" size={40}/></div>;
 return <div className="page"><PageHeading title={settings.title} description={settings.description} rows={rows} onAdd={isAudit?undefined:()=>setForm(true)} addLabel={`Add ${settings.singular}`}/>{module==='opportunities'&&<div className="mb-5 flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-muted-foreground">Open pipeline <strong className="ml-2 text-foreground">{money(rows.filter(r=>!['Won','Lost'].includes(r.status)).reduce((sum,r)=>sum+r.amount,0))}</strong></span><div className="flex gap-1"><Button variant={board?'secondary':'ghost'} onClick={()=>setBoard(true)}><Columns3/>Board</Button><Button variant={!board?'secondary':'ghost'} onClick={()=>setBoard(false)}><List/>List</Button></div></div>}
 <div className={board?'mb-5':'panel'}><div className="toolbar"><div className="toolbar-search"><Search/><Input placeholder={`Search ${settings.title.toLowerCase()}...`} aria-label={`Search ${settings.title.toLowerCase()}`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><div className="flex flex-wrap gap-2"><select aria-label="Filter by status" className="select-control" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option>All statuses</option>{statuses[module].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter by owner" className="select-control" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1);}}><option>All owners</option>{Array.from(new Set(scoped(module).map(r=>r.owner))).map(o=><option key={o}>{o}</option>)}</select><Button variant="outline" size="icon" title="Sort by name" aria-label="Sort by name" onClick={()=>setSort(!sort)}><ArrowUpDown/></Button></div></div>
 {!board&&<><div className="table-scroll"><table className="data-table"><thead><tr><th>{isAudit?'Event':isTask?'Subject':module==='opportunities'?'Opportunity':'Name'}</th>{isContact&&<th>Contact</th>}{module==='leads'&&<th>Source / value</th>}{module==='opportunities'&&<><th>Amount</th><th>Probability</th></>}{isTask&&<th>Type / due date</th>}{isAudit&&<th>Module / record</th>}{module==='users'&&<th>Role</th>}<th>{module==='opportunities'?'Stage':'Status'}</th><th>{isAudit?'Performed by':module==='users'?'Email':'Owner'}</th><th>{isAudit?'Date':'Actions'}</th></tr></thead><tbody>{visible.map((r,i)=><tr key={r.id}><td><div className="flex items-center gap-3">{(isContact||module==='users')&&<Avatar name={r.name} className={['','blue','violet','amber'][i%4]}/>}<div><div className="name">{r.name}</div><div className="sub">{r.company} · {r.id}</div></div></div></td>{isContact&&<td><div>{r.email}</div><div className="sub">{r.phone}</div></td>}{module==='leads'&&<td>{r.source}<div className="sub">{money(r.amount)}</div></td>}{module==='opportunities'&&<><td className="font-semibold">{money(r.amount)}</td><td>{r.probability}%<div className="sub">{r.date}</div></td></>}{isTask&&<td>{r.type}<div className="sub">{r.date}</div></td>}{isAudit&&<td>{r.company}<div className="sub">{r.related||'—'}</div></td>}{module==='users'&&<td><Status value={r.role}/></td>}<td><Status value={r.status}/></td><td>{module==='users'?r.email:<div className="flex items-center gap-2"><Avatar name={r.owner} className={['','amber','blue','violet'][i%4]}/>{r.owner}</div>}</td><td>{isAudit?r.date:<div className="record-actions"><Button variant="ghost" size="icon" title="View details" aria-label={`View ${r.name}`} onClick={()=>setDetail(r)}><Eye/></Button><Button variant="ghost" size="icon" title="Edit record" aria-label={`Edit ${r.name}`} onClick={()=>setForm(r)}><Pencil/></Button><Button variant="ghost" size="icon" title="Delete record" aria-label={`Delete ${r.name}`} onClick={()=>setDeleting(r)}><Trash2/></Button></div>}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty">No records match your filters.</div>}</div><div className="panel-footer"><span>Showing {rows.length?(safePage-1)*7+1:0}–{Math.min(safePage*7,rows.length)} of {rows.length} records</span><div className="flex items-center gap-2"><Button variant="outline" size="icon" aria-label="Previous page" disabled={safePage===1} onClick={()=>setPage(safePage-1)}><ChevronLeft/></Button><span>{safePage} / {pageCount}</span><Button variant="outline" size="icon" aria-label="Next page" disabled={safePage===pageCount} onClick={()=>setPage(safePage+1)}><ChevronRight/></Button></div></div></>}
 </div>{board&&<div className="pipeline-board">{statuses.opportunities.map(stage=><div className="pipeline-column" key={stage}><div className="pipeline-title">{stage}<span>{rows.filter(r=>r.status===stage).length}</span></div>{rows.filter(r=>r.status===stage).map(r=><div className="deal-card" key={r.id}><div className="flex justify-between items-start gap-1"><h3>{r.name}</h3><Button variant="ghost" size="icon" aria-label={`Edit ${r.name}`} onClick={()=>setForm(r)}><Pencil/></Button></div><p>{r.company}</p><strong>{money(r.amount)}</strong><div className="deal-bottom"><Avatar name={r.owner}/><span>{r.probability}% probability</span></div><select className="select-control" aria-label={`Stage for ${r.name}`} value={r.status} onChange={e=>changeStatus(r,e.target.value)}>{statuses.opportunities.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>)}</div>}
 {form&&<RecordForm module={module} record={form===true?undefined:form} onClose={()=>setForm(null)}/>}
 {detail&&<Dialog open onOpenChange={open=>{if(!open)setDetail(null);}}><DialogContent className="form-dialog"><DialogTitle>{detail.name}</DialogTitle><DialogDescription>{detail.company} · {detail.id}</DialogDescription><dl className="detail-grid">{Object.entries(detail).filter(([k,v])=>v!==''&&!['name','company','id','amount','probability','role'].includes(k)).map(([key,value])=><div key={key}><dt>{key[0].toUpperCase()+key.slice(1)}</dt><dd>{String(value)}</dd></div>)}{(module==='opportunities'||module==='leads')&&<><div><dt>Value</dt><dd>{money(detail.amount)}</dd></div><div><dt>Weighted pipeline</dt><dd>{money(detail.amount*detail.probability/100)}</dd></div></>}</dl><div className="details-actions"><Button onClick={()=>{setForm(detail);setDetail(null);}}><Pencil/>Edit record</Button>{module==='leads'&&detail.status==='Qualified'&&<Button variant="outline" onClick={()=>{convert(detail);setDetail(null);toast.success('Lead converted to customer');}}><ArrowRightLeft/>Convert to customer</Button>}{isTask&&detail.status==='Planned'&&<Button variant="outline" onClick={()=>{changeStatus(detail,'Completed');setDetail(null);}}><Check/>Mark complete</Button>}{module==='users'&&<Button variant="outline" onClick={()=>{changeStatus(detail,detail.status==='Active'?'Inactive':'Active');setDetail(null);}}>{detail.status==='Active'?'Deactivate':'Activate'} user</Button>}</div></DialogContent></Dialog>}
 {deleting&&<Dialog open onOpenChange={open=>{if(!open)setDeleting(null);}}><DialogContent><DialogTitle>Delete {settings.singular}?</DialogTitle><DialogDescription>“{deleting.name}” will be removed from this workspace. This cannot be undone.</DialogDescription><div className="form-actions"><Button variant="outline" onClick={()=>setDeleting(null)}>Cancel</Button><Button variant="destructive" onClick={()=>{remove(module,deleting.id);setDeleting(null);toast.success('Record deleted');}}>Delete {settings.singular}</Button></div></DialogContent></Dialog>}
 <div className="page-footer"><span>© {new Date().getFullYear()} AcxiomCRM. All rights reserved.</span><span>Sample workspace · Changes last until refresh</span></div></div>;
}
